name: .NET Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x
  
    - name: Restore NuGet packages
      run: dotnet restore src/Serverless/**/*.csproj
  
    - name: Build
      run: dotnet build src/Serverless/**/*.csproj
